
one element value
---
```{r}
[[]] # atomic vector or list
```

* 位置

* 元素名稱

```{r}
$ # list
```

multiple element values

```{r}
[]
```

 * 多個位置：[c(1, 2, 5)]
 * 多個元素名稱：[c("name1", "name2", "name3")]
 
 
 
```{r}
 # "John", "TRUE"
list("John", 178, TRUE)[c(1, 3)]
```
相當於
```{r}
list("John", TRUE)
```

 
 
```{r}
list(name = "John", height = 178, married = TRUE)[c("name","married")]
```
 
```{r}
list(name = "John", height = 178, married = TRUE)[c(1,3)]
```
 
 
 
 
 
 相當於
```{r}
list(name = "John", married = TRUE)
```
 
  ##
 #從小清單開始架構出大清單
 
 #步驟一（小清單）
```{r} 
list("john")
list(35)
list(
  name="Marry",
  age=32
)
list(
  name="Bill",
  age=5
)
list(
  name="Jane",
  age=3
)
```
 
 #步驟二（合併同質清單，以這題為例就是小孩子）
```{r} 
list("john")
list(35)
list(
  name="Marry",
  age=32
)
list(
  list(
  name="Bill",
  age=5
  ),
list(
  name="Jane",
  age=3
  )
)
```

#步驟三：整合所有清單在一個list，並把不需要用list的項目改為c，若是c裡面只有一個元素，則直接用那個元素表達就好了，以這題為例就是john跟john的年紀(35)
```{r} 
Johnsfamily <- list(
  name="john",
  age=35,
  spouse=list(
  name="Marry",
  age=32
  ),
  children=list(
    list(
      name="Bill",
      age=5
      ),
  list(
      name="Jane",
      age=3
    )
  )
)
```
 
```{r}
length(Johnsfamily)
names(Johnsfamily)
```
```{r}
Johnsfamily
length
```

```{r}
Sys.Date() # show the date today
```
```{r}
Johnsfamily[c(1, 2)]
Johnsfamily[c("name", "age")]
```
```{r}
Johnsfamily[["age"]] # or JohnsFamily[[2]]
Johnsfamily["age"] # or JohnsFamily[2]

typeof(Johnsfamily[["age"]]) # or JohnsFamily[[2]]
typeof(Johnsfamily["age"])# or JohnsFamily[2]
#兩個表達的資料形式不一樣
#兩個中括號，取的是Double(值)，相當於c()
#一個中括號，取的是List
```


```{r}
c("John"=98, "Mary"=90, "Ken"=72)[["John"]]
typeof(c("John"=98, "Mary"=90, "Ken"=72)[["John"]])

c("John"=98, "Mary"=90, "Ken"=72)["John"]
typeof(c("John"=98, "Mary"=90, "Ken"=72)["John"])
#相當於
c("John"=98)
  
```

***
John's age -15 = ?
```{r}
Johnsfamily[["age"]] - 15
c(35) - 15
```
ˆ
```{r}
Johnsfamily["age"] - 15#error
typeof(Johnsfamily["age"])
list( age = 35) - 15
#Error in Johnsfamily["age"] - 15 : non-numeric argument to binary operator
```
```{r}
c( age =35) -15 #c才會取出值
```


#清朝年號依序是：順治（1644-1661年）、康熙（1662-1722年）、雍正（1723-1735年）
```{r}
list(
  yearTitle= c("康熙", "順治", "順治", "康熙", "雍正", "順治", 
"康熙", "雍正", "康熙", "康熙"),
yearNumber = c(3, 3, 2, 2, 2, 2, 3, 3, 1, 3) 
) -> data0
```

```{r}
data0$yearTitle

data0$yearNumber
```

```{r}
addHowManyYears <- c(
  "順治"=1643,
  "康熙"=1661,
  "雍正"=1722
)
```

```{r}
addHowManyYears[c("康熙", "順治", "順治", "康熙", "雍正", "順治", 
"康熙", "雍正", "康熙", "康熙")] + data0$yearNumber

addHowManyYears[data0$yearTitle] + data0$yearNumber
```


#這邊就是在取上面的亂數
```{r}
sample(
  c(1, 2, 3, 4),
  10,
  T
) -> yearnumbers
dput(yearnumbers)
```

#這邊就是在取上面的亂數   
```{r}
#sample抽後放回的抽取
sample(
  c("順治", "康熙", "雍正"),
  10,
  TRUE
) -> randamYears
dput(randamYears)
```


```{r}
JohnsfamilyCopy <- Johnsfamily
JohnsfamilyCopy$name
JohnsfamilyCopy[["name"]] <- "John"
JohnsfamilyCopy[["name"]]
```

```{r}
# 取出錯誤的值，再去更正他
JohnsfamilyCopy[["name"]] <- "Waston"
#箭頭指向的方向就是被取代的值
JohnsfamilyCopy$name
```

```{r}
JohnsfamilyCopy <-
  Johnsfamily
```

```{r}
JohnsfamilyCopy[["name"]]
```
```{r}
JohnsfamilyCopy$children[[1]][[2]] <- 6
```
```{r}
JohnsfamilyCopy$children[[1]][[2]]
```
```{r}
threeKids <- c("Bill"=5, "Jane"=3, "Tom"=2)
```
```{r}
threeKidsCopy <- threeKids
```
```{r}
threeKidsCopy[[1]] <-6
threeKidsCopy[[3]] <-3
```
```{r}
threeKidsCopy <- threeKids
threeKidsCopy
```

```{r}
threeKidsCopy[c(1,3)]
```


```{r}
threeKidsCopy[c(1, 2)] <- 
  c(Bill=3, Jane=6)
```
```{r}
threeKidsCopy

```


```{r}
c("Tom", "Marry", "Tom")
```
```{r}
c("Tom", "Marry", "Tom")[3] -> "Ammy"
```
```{r}

```

```{r}
#a=1test
```
 
 
 