---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
example2 <- c("John", "Mary", "Bill", person4="Jack")
```

```{r}
example2[c(1:3)] -> example2
example2[c(1, 2, 3)] -> example2
```

```{r}
example2
```

```{r}
c(1, 2, 3)
1:3
```
```{r}
2:-1
```

```{r}
seq(from=2, to=12)

```

```{r}
seq(from=2, to=12, by=4)
#偷懶寫法比須依照順序
seq(2, 12, 4)
seq(from=2, to=12, by=3) #以不超過十二為主
```

```{r}
seq(from=2, to=12, length.out=13)
seq(from=2, to=12, length.out=2)
#偷懶寫法(因為length.out是在第四個，所以必須寫出來)
seq(2, 12, length.out=2)
#等份1格
seq(length.out=2, to=12, from=2)
#跟上面一樣
```

```{r}
example2Copy <- example2 <- c("John", "Mary", "Bill", person4="Jack")
example2Copy <- example2Copy[1:3]
example2Copy
example2Copy <- example2
example2Copy <- example2Copy[c(2, 4)]
example2Copy
```

```{r}
example2Copy <- example2 <- c("John", "Mary", "Bill", person4="Jack")
#比較直觀的刪除
example2Copy <- example2Copy[-c(1,3)]
example2Copy
```

```{r}
sample(LETTERS, 15, T) -> example3
example3
```

```{r}
example4 <- c("John", "Mary", "Bill", person4="Jack")
names(example4)
names(example4)[1:3] <- c("a", "b", "c")
example4
```

```{r}
example4
example4[[4]] <- ""
example4[[4]]
```


```{r}
example5 <- list("John", "Mary", "Bill", person4="Jack")
```

```{r}
example5Copy <- example5
example5Copy
```
```{r}
#比較一個中括號跟兩個中括號的差異
example5Copy[4] #取出

example5Copy[[4]] #取出值
```

```{r}
example5 <- list("John", "Mary", "Bill", person4="Jack")
#去掉1-3的元素後回存
example5[-(1:3)] -> example5
#把1-3的元素值設為虛空
example5[1:3] <- NULL
example5
example5[4] -> example5
example5

```


```{r}
example5[[4]] <- NULL
example5[[4]]

```
```{r}
#若要刪掉多個
example5[1:3] <- NULL
example5

```





















