---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
typeof(c("John", "Mary"))
typeof(c(2, 3.1412)) 
typeof(c(TRUE, TRUE, F))
```

```{r}
class(c("John", "Mary"))
class(c(2, 3.1412))
class(c(TRUE, TRUE, F))
#class已能做什麼事情分類
```

```{r}
c(2, 3.1412) + 3
#ckass numeric
```

```{r}
c("2", "3.1412") + 3
#class是character，所以不能加
```

```{r}
#character type to store date/time
c("2021-01-01 12:03:33")
class(c("2021-01-01 12:03:33"))

lubridate::ymd_hms(c("2021-01-01 12:03:33")) -> dateTimeRecord
dateTimeRecord
class(dateTimeRecord)
dateTimeRecord + 1
```

```{r}
commonClasses <- list()

# save three different atomic vectors
commonClasses$character <- c("John", "Mary", "Bill")
commonClasses$numeric <- c(2.3, 4, 7)
commonClasses$logical <- c(TRUE, T, F, FALSE)

commonClasses

```



###Factor
Code Book
  1 - AB
  2 - B
  3 - A
  4 - O

```{r}
bloodTypes <- c("AB", "AB", "A", "B", "A", "A", "B", "O", "O", "AB")
```

```{r}
mappingTable = c("AB"=1, "A"=2, "B"=3,"O"=4)
mappingTable[c("AB", "AB", "A", "B", "A", "A", "B", "O", "O", "AB")]
```

```{r}
mappingTable[c("AB", "AB", "A", "B", "A", "A", "B", "O", "O", "AB")] = c(1, 1, 2, 3,.....)
```

```{r}
bloodType = c(1, 1, 2, 3, 2, 2, 3, 4, 4, 1)
class(bloodType) #很危險，因為可以做加減，可能不小心誤改資料

```
```{r}
bloodType = factor(c(1, 1, 2, 3, 2, 2, 3, 4, 4, 1))
class(bloodType) #把numeric改成factor
```

```{r}
bloodType
```
```{r}
class(c("2021/10/30", "2021-10-30", "2021 October 30", "2021 Oct. 30"))
```

```{r}
lubridate::ymd(c("2021/10/30", "2021-10-30", "2021 October 30", "2021 Oct. 30"))
lubridate::ydm(c("2021/30/10", "2021-30-10", "2021 30 October", "2021 30 Oct."))
lubridate::mdy(c("10/30/2021", "10-30-2021", "October 30, 2021", "Oct. 30, 2021"))
lubridate::dmy(c("30/10/2021", "30-10-2021", "30 October, 2021", "30 Oct., 2021")) -> dateOne
```
```{r}
class(dateOne)
```

```{r}
# A parsed date data has Date class.
commonClasses$date <- lubridate::dmy(c("30/10/2021", "27-2-2021", "30 January, 2021", "30 mar., 2021"), tz = "Asia/Taipei")
commonClasses$date
class(commonClasses$date)
```


```{r}
commonClasses$date[[2]] +10
typeof(commonClasses$date[2])
typeof(commonClasses$date[[2]])
```

```{r}
"2022-05-02" |> lubridate::ymd()
"西元2022年5月2日" |> lubridate::ymd()
"民國81年5月2日" |> lubridate::ymd()
"民國1992年5月2日" |> lubridate::ymd()
```

```{r}
survey_fbf <-
  list(
    age=c(54, 32, 28, 20), # age
    gender=c("male", "female", "female", "male"), # gender
    residence=c("north", "south", "east", "east"), # residence
    income=c(100, 25, NA, 77) # income
  )
#都為atomic vector
#若要parsed的話，再list中的資料必須為atomic vector

df = data.frame(
  survey_fbf
)

df = data.frame(
  age=c(54, 32, 28, 20), # age
    gender=c("male", "female", "female", "male"), # gender
    residence=c("north", "south", "east", "east"), # residence
    income=c(100, 25, NA, 77)
)
# data.frame允許不用list呈現，只需要確認資料為atomic vector

survey_fbf$age
df$age
survey_fbf$gender[[2]]
#[ , ]
#[ ]
# df[raw,column] data.frame特殊用法
df[2 , 4]
df[2 , c("age", "gender", "residence", "income")]
df[2, ]
```

```{r}

```



















