# -*- coding: utf-8 -*-
#  """week 6 exercise.ipynb
#  
#  Automatically generated by Colaboratory.
#  
#  Original file is located at
#      https://colab.research.google.com/drive/1V10GLJSgsu_vC4oa6gyO7H1g3awkeDXr
#  
#  Source Link : <https://data.gov.tw/dataset/9346>
#  
#  各縣市四類公司 （"無限公司", "兩合公司", "有限公司", "股份有限公司"）資本額佔比有多少？
#  #  """
library(dplyr)
library(ggplot2)
googledrive::drive_deauth()
googledrive::drive_download("https://drive.google.com/file/d/1Cd4paAOsEs8Rec-4o8VNh6MfsXMLo-qs/view?usp=sharing", 
overwrite =T)

eachTypeCompanyCapital_long = readRDS(
  "eachTypeCompanyCapital_long.Rds"
)
ggplot(data=eachTypeCompanyCapital_long)+
  geom_col(
    mapping=aes(
      x=`縣 市 別`,
      y=CompanyTypeCapital, # 佔比的來源
      fill=CompanyType
    ),
    position="fill" # 
  )

#  """Or"""

Plot2 = function(){
  plt2 <- new.env()
  plt2$ggplot = ggplot(data=eachTypeCompanyCapital_long)
  plt2$geoms = list(
    geom_col(
      mapping=aes(
        x=`縣 市 別`,
        y=CompanyTypeCapital, # 佔比的來源
        fill=CompanyType
      ),
      position="fill" # 
    )
  )
  plt2$theme = list(
    theme(
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid.major.y = element_line(color="#c4d1d7")
    ),
    theme(
    axis.text.x = element_text(
    angle=45, hjust=1
    ))
  )

  plt2$make = function(){
  with(plt2, 
  ggplot+geoms+theme)}

  return(plt2)
}

plt2 = Plot2()
plt2$make()

#  """# Level sequence in CompanyType
#  
#  
#  #  """

eachTypeCompanyCapital_long$CompanyType |> factor() |> levels() |> dput()

eachTypeCompanyCapital_long |>
  mutate(
    CompanyType=factor(CompanyType, levels=c("兩合公司資本額", "無限公司資本額", "有限公司資本額",
"股份有限公司資本額"))
  ) ->
  eachTypeCompanyCapital_long

Plot2()$make()

#  """# The levels of `縣市別`
#  
#  Rearrange it to bring out a clear comparison story.
#  #  """

eachTypeCompanyCapital_long |>
  dplyr::filter(
    CompanyType == "股份有限公司資本額"
  ) |>
  arrange(佔比) |>
  pull(`縣 市 別`) |>
  as.character() -> graphLevels
graphLevels <- c(
  setdiff(graphLevels, c("臺灣地區","總計")),
  c("臺灣地區","總計"))
eachTypeCompanyCapital_long$`縣 市 別` <- 
  factor(eachTypeCompanyCapital_long$`縣 市 別`,
  levels=graphLevels)

# Regenerate plt2
plt2 = Plot2()
plt2$make()

eachTypeCompanyCapital_long |> 
  mutate(
    isWholeRegion = `縣 市 別` %in% c("臺灣地區","總計")
  ) -> eachTypeCompanyCapital_long

#  """依照isWholeRegion不同(vars(...))畫不同的plt2()在一個row(nrow=1)上，不同plt2()可以有不同x刻度（free_x)
#  
#  
#  #  """
plt2 = Plot2()
plt2$geoms = list(
  geom_col(
    mapping=aes(
      x=`縣 市 別`,
      y=CompanyTypeCapital, # 佔比的來源
      fill=CompanyType
    ),
    position="fill",
    alpha=0.5 
  )
)
plt2$make()+facet_grid(cols = vars(isWholeRegion),
  scales="free_x", 
  space="free_x") + theme(
  strip.text = element_blank()
) -> plt2Final
plt2Final+
  scale_y_continuous(expand=c(0,0))

source("./R/makeup.R", echo=TRUE)
makeup = Makeup()
mk_geom_col = makeup$geom_col()

plt2$geoms = list(
  mk_geom_col$geom(
    mapping=aes(
      x=`縣 市 別`,
      y=CompanyTypeCapital, # 佔比的來源
      fill=CompanyType
    ),
    position="fill"
  )
)
plt2$make() +
  facet_grid(cols = vars(isWholeRegion),
    scales="free_x", 
    space="free_x") + 
  theme(
    strip.text = element_blank()
  ) + 
  mk_geom_col$scale_y_continuous() + makeup$theme() 
