# -*- coding: utf-8 -*-
#  """week 6.ipynb
#  
#  Automatically generated by Colaboratory.
#  
#  Original file is located at
#      https://colab.research.google.com/drive/1Y1ZCdaQyYlAM5KhpvgKA6Y0tIjl0rSgt
#  
#  # Data
#  
#    * <https://od.moi.gov.tw/api/v1/rest/datastore/301000000A-001661-009>
#  #  """

if(!require(showtext)) install.packages("showtext")
showtext::showtext_auto()
# library(ggplot2)
# # set our graph theme to use the google font and a classic white back ground
# theme_set(
#   theme(
#     text=element_text(family = "Noto Sans TC")
#   )+
#     theme_classic()
# )
# 
# googledrive::drive_deauth()
# googledrive::drive_download(
#   file=googledrive::as_id("https://drive.google.com/file/d/1K8IWyy7G9LAKewjVXMGD8kUbbvjGoRT7/view?usp=sharing"),
#   overwrite = T
# )
source("~/Github/111-1-econDV/R/marriageSupport.R", echo=TRUE)

library(readr)
marriage <- read_csv("marriage.csv")
head(marriage)

library(dplyr)
marriageTaoYuan = getMarriageTaoYuan(marriage)

marriageTaoYuan |>
  correctClass() -> marriageTaoYuan

# 結婚年齡
# X：以妻年齡來看
# Y：對數
library(ggplot2)
plt = new.env()
plt$ggplot = ggplot(data=marriageTaoYuan)
plt$geoms = list(
  geom_col(
    mapping=aes(
      x=female_age_or_spouse1,
      y=marry_pair
    ),
    size = 0, #input$size
    color= "white", #input$color
    position="stack", # sum across sites within same age group.
    fill = "#1746A2"
  )
)
plt$theme = list(
  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_line(color="#c4d1d7")
  )
)
plt$ggplot + plt$geoms 


+ plt$theme +
  scale_y_continuous(expand = c(0,0)) 


